apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: argocd
  source:
    path   : "argocd/prod/applications"
    repoURL: "https://github.com/plavez/argocd.git"
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true

